# Generated by Django 4.2.11 on 2024-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../default_profile_rkmhff', upload_to='images/'),
        ),
    ]
