# Generated by Django 4.2.11 on 2024-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Profile', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
