# Generated by Django 4.2.11 on 2024-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='product',
            new_name='owner',
        ),
    ]
