# Generated by Django 4.2.11 on 2024-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0003_alter_stocks_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='property_image',
            field=models.ImageField(default='default_profile_rkmhff', upload_to='images/'),
        ),
    ]
