# Generated by Django 4.2.11 on 2024-08-11 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stocks', '0007_alter_stocks_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='property_image',
        ),
    ]
